/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Trip = IDL.Record({
  'waiting_minutes' : IDL.Nat,
  'total_fare' : IDL.Float64,
  'timestamp' : Time,
  'is_night' : IDL.Bool,
  'distance_km' : IDL.Float64,
});
export const DriverProfile = IDL.Record({
  'name' : IDL.Text,
  'upi_id' : IDL.Text,
  'phone' : IDL.Text,
  'licence' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTrip' : IDL.Func([IDL.Float64, IDL.Nat, IDL.Float64, IDL.Bool], [], []),
  'getLast10Trips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getProfile' : IDL.Func([], [DriverProfile], ['query']),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Trip = IDL.Record({
    'waiting_minutes' : IDL.Nat,
    'total_fare' : IDL.Float64,
    'timestamp' : Time,
    'is_night' : IDL.Bool,
    'distance_km' : IDL.Float64,
  });
  const DriverProfile = IDL.Record({
    'name' : IDL.Text,
    'upi_id' : IDL.Text,
    'phone' : IDL.Text,
    'licence' : IDL.Text,
  });
  
  return IDL.Service({
    'addTrip' : IDL.Func([IDL.Float64, IDL.Nat, IDL.Float64, IDL.Bool], [], []),
    'getLast10Trips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getProfile' : IDL.Func([], [DriverProfile], ['query']),
    'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };